# Basic Site Settings
locale: "en-US"
title: "Welcome to Yongjie's Homepage"
title_separator: "-"
name: &name "Yongjie Yang"
description: &description "4th year Ph.D. Candidate in University of Pittsburgh"
url: https://yud42.github.io
baseurl: "" # No subpath for the site
repository: "lijinlunbeng/yangyongjie.github.io"

# Site Author Information
author:
  avatar: "yue_profile_photo.png"
  name: "Yongjie Yang 「杨永杰」"
  bio: "Ph.D. Candidate in University of Pittsburgh"
  location: "Pittsburgh, PA"
  employer: "University of Pittsburgh"
  email: "yud42@pitt.edu"
  googlescholar: "https://scholar.google.com/citations?user=EPop_bEAAAAJ&hl=en"
  linkedin: "https://www.linkedin.com/in/yongjie-yang-60b427183/"

# Publication Categories
publication_category:
  conference:
    title: "Conference Papers"
  journal:
    title: "Journal Articles"
  workshop:
    title: "Workshop Papers"

# Collections
collections:
  publications:
    output: true
    permalink: /:collection/:path/
  teaching:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/

# Defaults for Pages
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true

# Remove Blog Pagination and Tags/Categories
permalink: /:categories/:title/
timezone: Etc/UTC
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - node_modules
  - vendor

# Markdown and Highlighter
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true

# Plugins
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji

# Archives (Remove Blog-Related Archives)
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Social Sharing (Removed Blog-Specific Social Sharing)
social:
  type: Person
  links:
    - "https://www.linkedin.com/in/yongjie-yang-60b427183/"
    - "https://scholar.google.com/citations?user=EPop_bEAAAAJ&hl=en"

# Disable Comments and Blog Features
comments:
  provider: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed
